module.exports = {
  apps: [
    {
      name: "astronomy-pathshala-api",
      cwd: __dirname,
      script: "dist/server.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.PM2_MAX_MEMORY_RESTART || "512M",
      exp_backoff_restart_delay: 1000,
      min_uptime: "10s",
      max_restarts: 10,
      kill_timeout: 15000,
      listen_timeout: 10000,
      merge_logs: false,
      time: false,
      env: {
        NODE_ENV: "development",
        HOST: process.env.HOST || "0.0.0.0",
        PORT: process.env.PORT || "5000",
        TRUST_PROXY: process.env.TRUST_PROXY || "false",
        LOG_LEVEL: process.env.LOG_LEVEL || "debug",
      },
      env_production: {
        NODE_ENV: "production",
        HOST: process.env.HOST || "0.0.0.0",
        PORT: process.env.PORT || "5000",
        TRUST_PROXY: process.env.TRUST_PROXY || "1",
        LOG_LEVEL: process.env.LOG_LEVEL || "info",
      },
    },
  ],
};
